In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\LeLuu\Documents\Python_Practice\Challenge_438\currency_data.csv")

In [3]:
df

,Subgroup Name,Order,Currency,2022-12-30,2023-01-25,2023-01-03,2023-01-29,2022-12-02,2022-12-17,2022-12-03,...,2023-01-18,2023-01-16,2023-01-17,2023-01-19,2023-01-20,2023-01-21,2023-01-24,2023-01-26,2023-01-27,2023-01-28
0,XXX,7,JPY,1.310439e+06,4.699288e+05,1.328173e+06,1.763119e+06,2.098947e+06,1.620982e+06,2.098947e+06,...,1.814876e+06,1.817753e+06,1.790167e+06,1.184014e+06,1.045576e+06,1.045576e+06,1.659750e+05,1.717234e+06,1.763119e+06,1.763119e+06
1,XXX,3,CHF,5.559135e+06,5.493002e+06,5.570408e+06,5.478856e+06,5.535687e+06,5.520498e+06,5.535687e+06,...,5.553344e+06,5.482472e+06,5.516953e+06,5.521213e+06,5.483930e+06,5.483930e+06,5.480296e+06,5.478610e+06,5.478856e+06,5.478856e+06
2,XXX,8,NOK,9.893030e+04,9.632987e+04,9.796724e+04,9.698868e+04,1.008924e+05,9.908285e+04,1.008924e+05,...,9.717710e+04,9.715905e+04,9.771600e+04,9.717710e+04,9.723641e+04,9.723641e+04,9.703576e+04,9.687098e+04,9.698868e+04,9.698868e+04
3,XXX,10,SGD,4.893866e+06,4.898640e+06,4.967976e+06,4.923038e+06,4.937097e+06,4.889306e+06,4.937097e+06,...,4.935467e+06,4.929850e+06,4.928374e+06,4.906881e+06,4.904371e+06,4.904371e+06,4.903197e+06,4.929148e+06,4.923038e+06,4.923038e+06
4,XXX,6,HKD,1.208400e+06,1.180435e+06,1.222644e+06,1.185580e+06,1.229903e+06,1.222922e+06,1.229903e+06,...,1.194336e+06,1.194246e+06,1.195749e+06,1.189914e+06,1.186677e+06,1.186677e+06,1.183761e+06,1.183416e+06,1.185580e+06,1.185580e+06
5,XXX,1,AUD,2.476336e+06,2.421401e+06,2.488172e+06,2.432361e+06,2.463704e+06,2.422323e+06,2.463704e+06,...,2.432096e+06,2.474030e+06,2.462630e+06,2.394987e+06,2.411359e+06,2.411359e+06,2.412697e+06,2.430967e+06,2.432361e+06,2.432361e+06
6,XXX,12,ZAR,2.650430e+03,2.580640e+03,2.687070e+03,2.585050e+03,2.614020e+03,2.574450e+03,2.614020e+03,...,2.642030e+03,2.633570e+03,2.621030e+03,2.575580e+03,2.600700e+03,2.600700e+03,2.581810e+03,2.579600e+03,2.585050e+03,2.585050e+03
7,XXX,5,GBP,1.578951e+07,1.563967e+07,1.716226e+07,1.564485e+07,7.583115e+08,1.661467e+07,7.583115e+08,...,2.042677e+08,2.014220e+08,2.031771e+08,1.565693e+07,1.569755e+07,1.569755e+07,1.563268e+07,1.565812e+07,1.564485e+07,1.564485e+07
8,XXX,4,EUR,1.012424e+09,1.015132e+09,1.015747e+09,1.015807e+09,1.035696e+09,6.126561e+08,1.035696e+09,...,1.287776e+09,1.483382e+09,1.273909e+09,1.022510e+09,1.007904e+09,1.007904e+09,1.016248e+09,1.023924e+09,1.015807e+09,1.015807e+09
9,XXX,2,CAD,2.790527e+06,2.483608e+06,2.860342e+06,2.474172e+06,2.122770e+06,2.590117e+06,2.122770e+06,...,2.533098e+06,2.648725e+06,2.605227e+06,2.522864e+06,2.515689e+06,2.515689e+06,2.536008e+06,2.461185e+06,2.474172e+06,2.474172e+06
10,XXX,9,SEK,6.299323e+05,6.313528e+05,6.320753e+05,6.286157e+05,6.465366e+05,6.381562e+05,6.465366e+05,...,6.313633e+05,6.240736e+05,6.268713e+05,6.304696e+05,6.307941e+05,6.307941e+05,6.343809e+05,6.298066e+05,6.286157e+05,6.286157e+05
11,XXX,11,USD,1.171122e+09,1.396840e+09,1.191989e+09,1.402597e+09,2.023533e+09,2.786621e+09,2.023533e+09,...,1.089071e+09,8.092142e+08,1.089044e+09,1.085394e+09,1.083024e+09,1.083024e+09,1.400655e+09,1.400338e+09,1.402597e+09,1.402597e+09
12,XXX,13,Total cve,2.218306e+09,2.445289e+09,2.244069e+09,2.453033e+09,3.836679e+09,3.434898e+09,3.836679e+09,...,2.600309e+09,2.513289e+09,2.585357e+09,2.142010e+09,2.124904e+09,2.124904e+09,2.449951e+09,2.458850e+09,2.453033e+09,2.453033e+09

In [4]:
#get list of columns
columns = df.columns.tolist()

In [5]:
columns

['Subgroup Name',
 'Order',
 'Currency',
 '2022-12-30',
 '2023-01-25',
 '2023-01-03',
 '2023-01-29',
 '2022-12-02',
 '2022-12-17',
 '2022-12-03',
 '2022-12-29',
 '2022-12-04',
 '2022-12-05',
 '2022-12-07',
 '2022-12-06',
 '2023-01-23',
 '2022-12-12',
 '2022-12-08',
 '2022-12-09',
 '2022-12-10',
 '2022-12-23',
 '2022-12-11',
 '2022-12-13',
 '2022-12-14',
 '2023-01-14',
 '2022-12-15',
 '2022-12-20',
 '2022-12-16',
 '2022-12-18',
 '2022-12-19',
 '2022-12-21',
 '2022-12-26',
 '2022-12-22',
 '2023-01-09',
 '2022-12-24',
 '2022-12-25',
 '2022-12-27',
 '2022-12-28',
 '2023-01-02',
 '2022-12-31',
 '2023-01-13',
 '2023-01-01',
 '2023-01-04',
 '2023-01-07',
 '2023-01-05',
 '2023-01-06',
 '2023-01-22',
 '2023-01-08',
 '2023-01-10',
 '2023-01-11',
 '2023-01-12',
 '2023-01-30',
 '2023-01-15',
 '2023-01-18',
 '2023-01-16',
 '2023-01-17',
 '2023-01-19',
 '2023-01-20',
 '2023-01-21',
 '2023-01-24',
 '2023-01-26',
 '2023-01-27',
 '2023-01-28']

In [9]:
item_removed = ['Subgroup Name','Order','Currency']
for item in item_removed:
    columns.remove(item)

In [10]:
columns

['2022-12-30',
 '2023-01-25',
 '2023-01-03',
 '2023-01-29',
 '2022-12-02',
 '2022-12-17',
 '2022-12-03',
 '2022-12-29',
 '2022-12-04',
 '2022-12-05',
 '2022-12-07',
 '2022-12-06',
 '2023-01-23',
 '2022-12-12',
 '2022-12-08',
 '2022-12-09',
 '2022-12-10',
 '2022-12-23',
 '2022-12-11',
 '2022-12-13',
 '2022-12-14',
 '2023-01-14',
 '2022-12-15',
 '2022-12-20',
 '2022-12-16',
 '2022-12-18',
 '2022-12-19',
 '2022-12-21',
 '2022-12-26',
 '2022-12-22',
 '2023-01-09',
 '2022-12-24',
 '2022-12-25',
 '2022-12-27',
 '2022-12-28',
 '2023-01-02',
 '2022-12-31',
 '2023-01-13',
 '2023-01-01',
 '2023-01-04',
 '2023-01-07',
 '2023-01-05',
 '2023-01-06',
 '2023-01-22',
 '2023-01-08',
 '2023-01-10',
 '2023-01-11',
 '2023-01-12',
 '2023-01-30',
 '2023-01-15',
 '2023-01-18',
 '2023-01-16',
 '2023-01-17',
 '2023-01-19',
 '2023-01-20',
 '2023-01-21',
 '2023-01-24',
 '2023-01-26',
 '2023-01-27',
 '2023-01-28']

In [11]:
df_melt = pd.melt(df,id_vars=['Subgroup Name','Order','Currency'],value_vars=columns)

In [12]:
df_melt

    Subgroup Name  Order   Currency    variable         value
0             XXX      7        JPY  2022-12-30  1.310439e+06
1             XXX      3        CHF  2022-12-30  5.559135e+06
2             XXX      8        NOK  2022-12-30  9.893030e+04
3             XXX     10        SGD  2022-12-30  4.893866e+06
4             XXX      6        HKD  2022-12-30  1.208400e+06
..            ...    ...        ...         ...           ...
775           XXX      4        EUR  2023-01-28  1.015807e+09
776           XXX      2        CAD  2023-01-28  2.474172e+06
777           XXX      9        SEK  2023-01-28  6.286157e+05
778           XXX     11        USD  2023-01-28  1.402597e+09
779           XXX     13  Total cve  2023-01-28  2.453033e+09

[780 rows x 5 columns]

In [13]:
df_melt.sort_values(by=['Order','variable'], inplace=True)

In [14]:
df_melt

    Subgroup Name  Order   Currency    variable         value
57            XXX      1        AUD  2022-12-02  2.463704e+06
83            XXX      1        AUD  2022-12-03  2.463704e+06
109           XXX      1        AUD  2022-12-04  2.463704e+06
122           XXX      1        AUD  2022-12-05  2.417655e+06
148           XXX      1        AUD  2022-12-06  2.402520e+06
..            ...    ...        ...         ...           ...
753           XXX     13  Total cve  2023-01-26  2.458850e+09
766           XXX     13  Total cve  2023-01-27  2.453033e+09
779           XXX     13  Total cve  2023-01-28  2.453033e+09
51            XXX     13  Total cve  2023-01-29  2.453033e+09
636           XXX     13  Total cve  2023-01-30  2.183576e+09

[780 rows x 5 columns]

In [15]:
df_melt.pivot(index=['Subgroup Name','Order','Currency'], columns='variable', values='value').reset_index()

variable,Subgroup Name,Order,Currency,2022-12-02,2022-12-03,2022-12-04,2022-12-05,2022-12-06,2022-12-07,2022-12-08,...,2023-01-21,2023-01-22,2023-01-23,2023-01-24,2023-01-25,2023-01-26,2023-01-27,2023-01-28,2023-01-29,2023-01-30
0,XXX,1,AUD,2.463704e+06,2.463704e+06,2.463704e+06,2.417655e+06,2.402520e+06,2.422793e+06,2.417712e+06,...,2.411359e+06,2.411359e+06,2.423831e+06,2.412697e+06,2.421401e+06,2.430967e+06,2.432361e+06,2.432361e+06,2.432361e+06,2.408007e+06
1,XXX,2,CAD,2.122770e+06,2.122770e+06,2.122770e+06,2.005153e+06,1.974667e+06,1.974145e+06,2.014865e+06,...,2.515689e+06,2.515689e+06,2.528163e+06,2.536008e+06,2.483608e+06,2.461185e+06,2.474172e+06,2.474172e+06,2.474172e+06,2.463845e+06
2,XXX,3,CHF,5.535687e+06,5.535687e+06,5.535687e+06,5.515913e+06,5.524623e+06,5.516353e+06,5.513333e+06,...,5.483930e+06,5.483930e+06,5.474015e+06,5.480296e+06,5.493002e+06,5.478610e+06,5.478856e+06,5.478856e+06,5.478856e+06,5.469242e+06
3,XXX,4,EUR,1.035696e+09,1.035696e+09,1.035696e+09,1.015775e+09,1.016543e+09,1.012579e+09,1.016183e+09,...,1.007904e+09,1.007904e+09,1.164691e+09,1.016248e+09,1.015132e+09,1.023924e+09,1.015807e+09,1.015807e+09,1.015807e+09,1.017932e+09
4,XXX,5,GBP,7.583115e+08,7.583115e+08,7.583115e+08,7.543718e+08,5.225553e+08,8.103950e+08,8.087263e+08,...,1.569755e+07,1.569755e+07,1.569664e+07,1.563268e+07,1.563967e+07,1.565812e+07,1.564485e+07,1.564485e+07,1.564485e+07,1.563593e+07
5,XXX,6,HKD,1.229903e+06,1.229903e+06,1.229903e+06,1.236850e+06,1.239815e+06,1.230768e+06,1.226519e+06,...,1.186677e+06,1.186677e+06,1.186747e+06,1.183761e+06,1.180435e+06,1.183416e+06,1.185580e+06,1.185580e+06,1.185580e+06,1.187478e+06
6,XXX,7,JPY,2.098947e+06,2.098947e+06,2.098947e+06,1.084926e+06,2.075634e+04,5.954606e+05,1.686819e+06,...,1.045576e+06,1.045576e+06,1.107835e+06,1.659750e+05,4.699288e+05,1.717234e+06,1.763119e+06,1.763119e+06,1.763119e+06,1.544514e+06
7,XXX,8,NOK,1.008924e+05,1.008924e+05,1.008924e+05,9.952621e+04,9.905464e+04,9.876874e+04,9.884481e+04,...,9.723641e+04,9.723641e+04,9.751928e+04,9.703576e+04,9.632987e+04,9.687098e+04,9.698868e+04,9.698868e+04,9.698868e+04,9.622983e+04
8,XXX,9,SEK,6.465366e+05,6.465366e+05,6.465366e+05,6.439339e+05,6.444769e+05,6.453327e+05,6.447168e+05,...,6.307941e+05,6.307941e+05,6.323263e+05,6.343809e+05,6.313528e+05,6.298066e+05,6.286157e+05,6.286157e+05,6.286157e+05,6.293849e+05
9,XXX,10,SGD,4.937097e+06,4.937097e+06,4.937097e+06,4.969645e+06,4.952567e+06,4.921580e+06,4.909043e+06,...,4.904371e+06,4.904371e+06,4.915460e+06,4.903197e+06,4.898640e+06,4.929148e+06,4.923038e+06,4.923038e+06,4.923038e+06,4.938886e+06
10,XXX,11,USD,2.023533e+09,2.023533e+09,2.023533e+09,2.031831e+09,2.323977e+09,2.313101e+09,2.303075e+09,...,1.083024e+09,1.083024e+09,1.266657e+09,1.400655e+09,1.396840e+09,1.400338e+09,1.402597e+09,1.402597e+09,1.402597e+09,1.131268e+09
11,XXX,12,ZAR,2.614020e+03,2.614020e+03,2.614020e+03,2.645920e+03,2.662470e+03,2.667980e+03,2.660790e+03,...,2.600700e+03,2.600700e+03,2.595200e+03,2.581810e+03,2.580640e+03,2.579600e+03,2.585050e+03,2.585050e+03,2.585050e+03,2.569580e+03
12,XXX,13,Total cve,3.836679e+09,3.836679e+09,3.836679e+09,3.819955e+09,3.879937e+09,4.153483e+09,4.146499e+09,...,2.124904e+09,2.124904e+09,2.465414e+09,2.449951e+09,2.445289e+09,2.458850e+09,2.453033e+09,2.453033e+09,2.453033e+09,2.183576e+09